spring.application.name=ms-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-autor
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/autores/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-libro
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/libros/**